name: Reprolang

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'reprolang/**'

jobs:
  reprolang-parser-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/asdf
        with:
          js: true
      - run: ./cmd/scip/tests/reprolang/generate-tree-sitter-parser.sh
      - run: git diff --exit-code
